name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      # - develop
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: 'stable'
      - name: Flutter build web
        working-directory: ./example
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release --base-href /flutter_scrollview_observer/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'